-- MySQL Script generated by MySQL Workbench
-- Tue Oct  7 10:48:50 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema e22507733_db1
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema e22507733_db1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `e22507733_db1` ;
USE `e22507733_db1` ;

-- -----------------------------------------------------
-- Table `e22507733_db1`.`t_ville_vll`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `e22507733_db1`.`t_ville_vll` (
  `vll_id` INT NOT NULL AUTO_INCREMENT,
  `vll_code_postal` INT NOT NULL,
  `vll_nom` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`vll_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `e22507733_db1`.`t_compte_cpt`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `e22507733_db1`.`t_compte_cpt` (
  `cpt_id` INT NOT NULL AUTO_INCREMENT,
  `cpt_pseudo` VARCHAR(100) NOT NULL,
  `cpt_mdp` CHAR(64) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL,
  `cpt_etat` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cpt_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `e22507733_db1`.`t_profil_pfl`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `e22507733_db1`.`t_profil_pfl` (
  `pfl_id` INT NOT NULL AUTO_INCREMENT,
  `pfl_nom` VARCHAR(80) NOT NULL,
  `pfl_prenom` VARCHAR(80) NOT NULL,
  `pfl_email` VARCHAR(150) NOT NULL,
  `pfl_telephone` CHAR(12) NULL,
  `pfl_date_naissance` DATE NOT NULL,
  `pfl_adresse` VARCHAR(200) NULL,
  `pfl_statut` VARCHAR(45) NOT NULL,
  `vll_id` INT NOT NULL,
  `cpt_id` INT NOT NULL,
  PRIMARY KEY (`pfl_id`, `cpt_id`),
  INDEX `fk_t_profil_pfl_t_ville_vll_idx` (`vll_id` ASC) VISIBLE,
  INDEX `fk_t_profil_pfl_t_compte_cpt1_idx` (`cpt_id` ASC) VISIBLE,
  CONSTRAINT `fk_t_profil_pfl_t_ville_vll`
    FOREIGN KEY (`vll_id`)
    REFERENCES `e22507733_db1`.`t_ville_vll` (`vll_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_profil_pfl_t_compte_cpt1`
    FOREIGN KEY (`cpt_id`)
    REFERENCES `e22507733_db1`.`t_compte_cpt` (`cpt_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `e22507733_db1`.`t_actualite_act`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `e22507733_db1`.`t_actualite_act` (
  `act_id` INT NOT NULL AUTO_INCREMENT,
  `act_titre` VARCHAR(100) NOT NULL,
  `act_image` VARCHAR(100) NOT NULL,
  `act_date_ajout` DATETIME(1) NOT NULL,
  `act_contenu` VARCHAR(1500) NOT NULL,
  `cpt_id` INT NOT NULL,
  PRIMARY KEY (`act_id`),
  INDEX `fk_t_actualite_act_t_compte_cpt1_idx` (`cpt_id` ASC) VISIBLE,
  CONSTRAINT `fk_t_actualite_act_t_compte_cpt1`
    FOREIGN KEY (`cpt_id`)
    REFERENCES `e22507733_db1`.`t_compte_cpt` (`cpt_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `e22507733_db1`.`t_ressource_rsc`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `e22507733_db1`.`t_ressource_rsc` (
  `rsc_id` INT NOT NULL AUTO_INCREMENT,
  `rsc_nom` VARCHAR(100) NOT NULL,
  `rsc_photo` VARCHAR(100) NOT NULL,
  `rsc_description` VARCHAR(300) NOT NULL,
  `rsc_jauge` INT NOT NULL,
  `rsc_url` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`rsc_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `e22507733_db1`.`t_motif_mtf`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `e22507733_db1`.`t_motif_mtf` (
  `mtf_id` INT NOT NULL AUTO_INCREMENT,
  `mtf_intitule` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`mtf_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `e22507733_db1`.`t_indisponibilite_idp`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `e22507733_db1`.`t_indisponibilite_idp` (
  `idp_id` INT NOT NULL AUTO_INCREMENT,
  `idp_date_debut` DATETIME(1) NOT NULL,
  `idp_date_fin` DATETIME(1) NOT NULL,
  `idp_statut` VARCHAR(45) NOT NULL,
  `idp_commentaire` VARCHAR(600) NULL,
  `mtf_id` INT NOT NULL,
  PRIMARY KEY (`idp_id`),
  INDEX `fk_t_indisponibilite_idp_t_motif_mtf1_idx` (`mtf_id` ASC) VISIBLE,
  CONSTRAINT `fk_t_indisponibilite_idp_t_motif_mtf1`
    FOREIGN KEY (`mtf_id`)
    REFERENCES `e22507733_db1`.`t_motif_mtf` (`mtf_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `e22507733_db1`.`t_reservation_res`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `e22507733_db1`.`t_reservation_res` (
  `res_id` INT NOT NULL AUTO_INCREMENT,
  `res_nom` VARCHAR(100) NOT NULL,
  `res_date_debut` DATETIME(1) NOT NULL,
  `res_date_fin` DATETIME(1) NOT NULL,
  `res_bilan_reservation` VARCHAR(600) NOT NULL,
  `res_statut` VARCHAR(45) NOT NULL,
  `rsc_id` INT NOT NULL,
  PRIMARY KEY (`res_id`, `rsc_id`),
  INDEX `fk_t_reservation_res_t_ressource_rsc1_idx` (`rsc_id` ASC) VISIBLE,
  CONSTRAINT `fk_t_reservation_res_t_ressource_rsc1`
    FOREIGN KEY (`rsc_id`)
    REFERENCES `e22507733_db1`.`t_ressource_rsc` (`rsc_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `e22507733_db1`.`t_reunion_reu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `e22507733_db1`.`t_reunion_reu` (
  `reu_id` INT NOT NULL AUTO_INCREMENT,
  `reu_date_debut` DATETIME(1) NOT NULL,
  `reu_theme` VARCHAR(100) NOT NULL,
  `reu_lieu` VARCHAR(45) NOT NULL,
  `reu_fin` TIME NOT NULL,
  PRIMARY KEY (`reu_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `e22507733_db1`.`t_document_dcm`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `e22507733_db1`.`t_document_dcm` (
  `dcm_id` INT NOT NULL AUTO_INCREMENT,
  `dcm_intitule` VARCHAR(100) NOT NULL,
  `dcm_url` VARCHAR(100) NOT NULL,
  `reu_id` INT NOT NULL,
  PRIMARY KEY (`dcm_id`),
  INDEX `fk_t_document_dcm_t_reunion_reu1_idx` (`reu_id` ASC) VISIBLE,
  CONSTRAINT `fk_t_document_dcm_t_reunion_reu1`
    FOREIGN KEY (`reu_id`)
    REFERENCES `e22507733_db1`.`t_reunion_reu` (`reu_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `e22507733_db1`.`t_message_msg`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `e22507733_db1`.`t_message_msg` (
  `msg_id` INT NOT NULL AUTO_INCREMENT,
  `msg_code` CHAR(20) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL,
  `msg_contenu` VARCHAR(600) NULL,
  `msg_email` VARCHAR(150) NOT NULL,
  `msg_reponse` VARCHAR(600) NULL,
  `cpt_id` INT NULL,
  `msg_date` DATETIME(1) NULL,
  PRIMARY KEY (`msg_id`),
  INDEX `fk_t_message_msg_t_compte_cpt1_idx` (`cpt_id` ASC) VISIBLE,
  UNIQUE INDEX `msg_code_UNIQUE` (`msg_code` ASC) VISIBLE,
  CONSTRAINT `fk_t_message_msg_t_compte_cpt1`
    FOREIGN KEY (`cpt_id`)
    REFERENCES `e22507733_db1`.`t_compte_cpt` (`cpt_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `e22507733_db1`.`t_participation_ptp`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `e22507733_db1`.`t_participation_ptp` (
  `cpt_id` INT NOT NULL,
  `reu_id` INT NOT NULL,
  `ptp_date_inscription` DATETIME(1) NOT NULL,
  PRIMARY KEY (`cpt_id`, `reu_id`),
  INDEX `fk_t_compte_cpt_has_t_reunion_reu_t_reunion_reu1_idx` (`reu_id` ASC) VISIBLE,
  INDEX `fk_t_compte_cpt_has_t_reunion_reu_t_compte_cpt1_idx` (`cpt_id` ASC) VISIBLE,
  CONSTRAINT `fk_t_compte_cpt_has_t_reunion_reu_t_compte_cpt1`
    FOREIGN KEY (`cpt_id`)
    REFERENCES `e22507733_db1`.`t_compte_cpt` (`cpt_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_compte_cpt_has_t_reunion_reu_t_reunion_reu1`
    FOREIGN KEY (`reu_id`)
    REFERENCES `e22507733_db1`.`t_reunion_reu` (`reu_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `e22507733_db1`.`t_inscription_isc`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `e22507733_db1`.`t_inscription_isc` (
  `cpt_id` INT NOT NULL,
  `res_id` INT NOT NULL,
  `isc_date` DATETIME(1) NOT NULL,
  `isc_role` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`cpt_id`, `res_id`),
  INDEX `fk_t_compte_cpt_has_t_reservation_res_t_reservation_res1_idx` (`res_id` ASC) VISIBLE,
  INDEX `fk_t_compte_cpt_has_t_reservation_res_t_compte_cpt1_idx` (`cpt_id` ASC) VISIBLE,
  CONSTRAINT `fk_t_compte_cpt_has_t_reservation_res_t_compte_cpt1`
    FOREIGN KEY (`cpt_id`)
    REFERENCES `e22507733_db1`.`t_compte_cpt` (`cpt_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_compte_cpt_has_t_reservation_res_t_reservation_res1`
    FOREIGN KEY (`res_id`)
    REFERENCES `e22507733_db1`.`t_reservation_res` (`res_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `e22507733_db1`.`t_etat_ett`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `e22507733_db1`.`t_etat_ett` (
  `rsc_id` INT NOT NULL,
  `idp_id` INT NOT NULL,
  PRIMARY KEY (`rsc_id`, `idp_id`),
  INDEX `fk_t_ressource_rsc_has_t_indisponibilite_idp_t_indisponibil_idx` (`idp_id` ASC) VISIBLE,
  INDEX `fk_t_ressource_rsc_has_t_indisponibilite_idp_t_ressource_rs_idx` (`rsc_id` ASC) VISIBLE,
  CONSTRAINT `fk_t_ressource_rsc_has_t_indisponibilite_idp_t_ressource_rsc1`
    FOREIGN KEY (`rsc_id`)
    REFERENCES `e22507733_db1`.`t_ressource_rsc` (`rsc_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_ressource_rsc_has_t_indisponibilite_idp_t_indisponibilit1`
    FOREIGN KEY (`idp_id`)
    REFERENCES `e22507733_db1`.`t_indisponibilite_idp` (`idp_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
